### ISSUE TITLE
Using Nvidia TensorRT in the Docker container

### ISSUE THREAD

**Issue by hupf80** [FieldRobotEvent/example_ws#10]
Hey Rick,

for our Project we are using Nvidia TensorRT. I tried several times to install TensorRT into the Docker-Container. But I never succeed.

Also I figured out, Nvidia Provides a separate Container with TensorRT.

Can you help me to figure out, how to install Nvidia TensorRT in to the container?
Or is it also possible to use the the Nvidia-Container in the robot_workspace?

To spefify my current issue:

I'm tring to install TensorRT in the dockerfile.

With the command from 
I[Nvidia Tensorrt Documentation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#maclearn-net-repo-install)
 
I used `sudo apt-get install libnvinfer8 libnvonnxparsers8 libnvparsers8 libnvinfer-plugin8`

The error Occurs `Unable to locate package`

The next way, after also the dev versions of the packages where not found, i tried to download the *deb file from the Nvidia-Page using wget into the Dockerfile, but it seems Nvidia has blocked the permissions, so wget is not able to dowoload the installer files.

The third version I tried, was to dowlonad the *deb file into the same dir as the dockerfile is, then to install TensorRT with `os="ubuntuxx04"
tag="cudax.x-trt8.x.x.x-ea-yyyymmdd"
sudo dpkg -i nv-tensorrt-repo-${os}-${tag}_1-1_amd64.deb
sudo apt-key add /var/nv-tensorrt-repo-${os}-${tag}/*.pub

sudo apt-get update
sudo apt-get install tensorrt`
As Showed in the [Debian Installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-debian) of the Nvidia Installation.
It was not possible because the installer with `dpkg` unpacked the *deb-file and the following `sudo apt-key add `-command tries to find the *pub files, which it can not be provided.

So may you have any hint for me, it would be really helpful.

Thanks in advance

Philipp :)

**Comment by Rick-v-E** [comment]
I do not know the specifics of TensorRT, but I would start with that container as `FROM` in your Dockerfile. In that container, you have to install ROS Noetic and probably make CUDA available within the docker. An example where I just copied the [ROS CUDA simulation container](https://github.com/FieldRobotEvent/competition_environment/blob/main/dockerfiles/ros_noetic_cuda/Dockerfile) with a different `FROM`:

```dockerfile
FROM nvcr.io/nvidia/tensorrt:21.11-py3:latest

# Setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -q -y --no-install-recommends \
        tzdata && \
    rm -rf /var/lib/apt/lists/*

# Install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    && rm -rf /var/lib/apt/lists/*

# Setup sources.list
RUN echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros1-latest.list

# Setup keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# Setup environment
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV ROS_DISTRO noetic

# Install ros packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ros-noetic-ros-base=1.5.0-1* \
        build-essential \    
        python3-rosdep \    
        python3-rosinstall \     
        python3-vcstools && \
    rosdep init && \
    rosdep update --rosdistro $ROS_DISTRO && \
    rm -rf /var/lib/apt/lists/*

# nvidia-container-runtime
# make sure that you add these to your docker file, otherwise it cannot access CUDA.
ENV NVIDIA_VISIBLE_DEVICES \
  ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
  ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

<< REST OF YOUR DOCKER FILE >>
```
For the event, we use [`nvidia-docker2`](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) to run the containers. See [this link](https://github.com/FieldRobotEvent/competition_environment/blob/main/doc/use_gpu_in_docker.md) for more details. Please try if this works on your computer.

We will sent an email around with a link to upload your robot container to test it on our hardware sometime next week.

Rick

**Comment by Rick-v-E** [comment]
Oh, btw, you need to make sure that the `FROM` docker image is derived from Ubuntu 20.04. Otherwise it is not possible to install ROS Noetic in it.

**Comment by hupf80** [comment]
@Rick-v-E Thank you for your reply!

It works fine for our Team. Our Container is now Based on the `FROM nvcr.io/nvidia/tensorrt:21.12-py3:latest` docker image, i had to figure out, which of the image version I have to use, but now it works fine!
